-- =============================================================================
-- MediTriaje 2.0 — Migración V004: Estructura Asistencial y Oferta de Atención
-- =============================================================================
-- Tablas:
--   1. INSTITUCION: Prestador de servicios de salud (IPS/EPS).
--   2. SEDE: Sede física o centro de atención médica.
--   3. ESPECIALIDAD: Especialidad médica con duración parametrizada de turnos.
--   4. PROFESIONAL: Profesional asistencial vinculado a usuario y especialidad.
--   5. DISPONIBILIDAD_SLOT: Turnos de agenda ofertados por administración.
--
-- Concesión de privilegios mínimos a MEDITRIAJE_APP según ADR-012.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. TABLA: INSTITUCION
-- -----------------------------------------------------------------------------
CREATE TABLE INSTITUCION (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    NIT VARCHAR2(20 CHAR) NOT NULL,
    RAZON_SOCIAL VARCHAR2(120 CHAR) NOT NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_INSTITUCION PRIMARY KEY (ID),
    CONSTRAINT UQ_INSTITUCION_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_INSTITUCION_NIT UNIQUE (NIT),
    CONSTRAINT CK_INSTITUCION_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
);

-- -----------------------------------------------------------------------------
-- 2. TABLA: SEDE
-- -----------------------------------------------------------------------------
CREATE TABLE SEDE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    INSTITUCION_ID NUMBER NOT NULL,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    NOMBRE VARCHAR2(80 CHAR) NOT NULL,
    DIRECCION VARCHAR2(120 CHAR) NOT NULL,
    CIUDAD VARCHAR2(60 CHAR) NOT NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_SEDE PRIMARY KEY (ID),
    CONSTRAINT UQ_SEDE_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_SEDE_INSTITUCION FOREIGN KEY (INSTITUCION_ID) REFERENCES INSTITUCION(ID),
    CONSTRAINT CK_SEDE_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
);

CREATE INDEX IX_SEDE_INSTITUCION ON SEDE (INSTITUCION_ID);

-- -----------------------------------------------------------------------------
-- 3. TABLA: ESPECIALIDAD
-- -----------------------------------------------------------------------------
CREATE TABLE ESPECIALIDAD (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    NOMBRE VARCHAR2(60 CHAR) NOT NULL,
    DURACION_SLOT_MIN NUMBER DEFAULT 20 NOT NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY (ID),
    CONSTRAINT UQ_ESPECIALIDAD_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_ESPECIALIDAD_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CK_ESPECIALIDAD_DURACION CHECK (DURACION_SLOT_MIN > 0),
    CONSTRAINT CK_ESPECIALIDAD_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
);

-- -----------------------------------------------------------------------------
-- 4. TABLA: PROFESIONAL
-- -----------------------------------------------------------------------------
CREATE TABLE PROFESIONAL (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    USUARIO_ID NUMBER NOT NULL,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    ESPECIALIDAD_ID NUMBER NOT NULL,
    REGISTRO_MEDICO VARCHAR2(30 CHAR) NOT NULL,
    NOMBRES VARCHAR2(60 CHAR) NOT NULL,
    APELLIDOS VARCHAR2(60 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT PK_PROFESIONAL PRIMARY KEY (ID),
    CONSTRAINT UQ_PROFESIONAL_USUARIO UNIQUE (USUARIO_ID),
    CONSTRAINT UQ_PROFESIONAL_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_PROFESIONAL_REGISTRO UNIQUE (REGISTRO_MEDICO),
    CONSTRAINT FK_PROFESIONAL_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    CONSTRAINT FK_PROFESIONAL_ESPECIALIDAD FOREIGN KEY (ESPECIALIDAD_ID) REFERENCES ESPECIALIDAD(ID)
);

CREATE INDEX IX_PROFESIONAL_ESPECIALIDAD ON PROFESIONAL (ESPECIALIDAD_ID);

-- -----------------------------------------------------------------------------
-- 5. TABLA: DISPONIBILIDAD_SLOT
-- -----------------------------------------------------------------------------
CREATE TABLE DISPONIBILIDAD_SLOT (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    PROFESIONAL_ID NUMBER NOT NULL,
    SEDE_ID NUMBER NOT NULL,
    ESPECIALIDAD_ID NUMBER NOT NULL,
    FECHA_HORA_INICIO TIMESTAMP WITH TIME ZONE NOT NULL,
    FECHA_HORA_FIN TIMESTAMP WITH TIME ZONE NOT NULL,
    MODALIDAD VARCHAR2(20 CHAR) DEFAULT 'PRESENCIAL' NOT NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'LIBRE' NOT NULL,
    CONSTRAINT PK_DISPONIBILIDAD_SLOT PRIMARY KEY (ID),
    CONSTRAINT UQ_SLOT_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_SLOT_PROFESIONAL FOREIGN KEY (PROFESIONAL_ID) REFERENCES PROFESIONAL(ID),
    CONSTRAINT FK_SLOT_SEDE FOREIGN KEY (SEDE_ID) REFERENCES SEDE(ID),
    CONSTRAINT FK_SLOT_ESPECIALIDAD FOREIGN KEY (ESPECIALIDAD_ID) REFERENCES ESPECIALIDAD(ID),
    CONSTRAINT CK_SLOT_HORAS CHECK (FECHA_HORA_FIN > FECHA_HORA_INICIO),
    CONSTRAINT CK_SLOT_MODALIDAD CHECK (MODALIDAD IN ('PRESENCIAL', 'TELEMEDICINA')),
    CONSTRAINT CK_SLOT_ESTADO CHECK (ESTADO IN ('LIBRE', 'OCUPADO', 'BLOQUEADO'))
);

CREATE INDEX IX_SLOT_BUSQUEDA ON DISPONIBILIDAD_SLOT (ESPECIALIDAD_ID, SEDE_ID, ESTADO, FECHA_HORA_INICIO);
CREATE INDEX IX_SLOT_SEDE ON DISPONIBILIDAD_SLOT (SEDE_ID);
-- En Oracle, TIMESTAMP WITH TIME ZONE no puede ser clave única directa (ORA-02329); se usa índice funcional UTC:
CREATE UNIQUE INDEX UQ_SLOT_PROFESIONAL_INICIO ON DISPONIBILIDAD_SLOT (PROFESIONAL_ID, SYS_EXTRACT_UTC(FECHA_HORA_INICIO));

-- -----------------------------------------------------------------------------
-- 6. CONCESIÓN DE PRIVILEGIOS MÍNIMOS A MEDITRIAJE_APP (ADR-012)
-- -----------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON INSTITUCION TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON SEDE TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON ESPECIALIDAD TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON PROFESIONAL TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON DISPONIBILIDAD_SLOT TO MEDITRIAJE_APP;
