-- =============================================================================
-- MediTriaje 2.0 — Migración V008: Módulo de Atención Clínica e Historia Clínica (M6.1)
-- =============================================================================
-- Tablas: DIAGNOSTICO_CIE10, ATENCION, SIGNO_VITAL, ATENCION_ENMIENDA, ALERGIA
-- Características críticas:
--   1. DIAGNOSTICO_CIE10: Catálogo reducido de patologías (solo SELECT para MEDITRIAJE_APP).
--   2. ATENCION: Acto médico profesional inmutable (ADR-008). Relación 1:1 con CITA.
--      Trigger TR_ATENCION_INMUTABILIDAD bloquea UPDATE de atenciones CERRADAS y DELETE total.
--   3. SIGNO_VITAL: Parámetros fisiológicos vinculados a la atención.
--      Trigger TR_SIGNO_VITAL_INMUTABILIDAD prohíbe INSERT/UPDATE/DELETE si la atención está CERRADA.
--   4. ATENCION_ENMIENDA: Aclaración append-only a atenciones cerradas (ADR-008).
--      Trigger TR_ENMIENDA_INMUTABILIDAD prohíbe UPDATE y DELETE, y exige que la atención esté CERRADA.
--   5. ALERGIA: Registro de hipersensibilidades del paciente.
--   6. Privilegios mínimos (ADR-012): MEDITRIAJE_APP no posee DELETE sobre ninguna tabla clínica,
--      ni UPDATE sobre ATENCION_ENMIENDA ni DML sobre DIAGNOSTICO_CIE10.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. DIAGNOSTICO_CIE10
-- -----------------------------------------------------------------------------
CREATE TABLE DIAGNOSTICO_CIE10 (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    CODIGO VARCHAR2(10 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(255 CHAR) NOT NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_DIAGNOSTICO_CIE10 PRIMARY KEY (ID),
    CONSTRAINT UQ_CIE10_CODIGO UNIQUE (CODIGO),
    CONSTRAINT CK_CIE10_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
);

-- -----------------------------------------------------------------------------
-- 2. ATENCION
-- -----------------------------------------------------------------------------
CREATE TABLE ATENCION (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    CITA_ID NUMBER NOT NULL,
    PACIENTE_ID NUMBER NOT NULL,
    PROFESIONAL_ID NUMBER NOT NULL,
    DIAGNOSTICO_PRINCIPAL_ID NUMBER,
    MOTIVO_CONSULTA VARCHAR2(500 CHAR),
    EVOLUCION VARCHAR2(4000 CHAR),
    INDICACIONES VARCHAR2(1000 CHAR),
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ABIERTA' NOT NULL,
    FECHA_CIERRE TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_ATENCION PRIMARY KEY (ID),
    CONSTRAINT UQ_ATENCION_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_ATENCION_CITA UNIQUE (CITA_ID),
    CONSTRAINT FK_ATENCION_CITA FOREIGN KEY (CITA_ID) REFERENCES CITA(ID),
    CONSTRAINT FK_ATENCION_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(ID),
    CONSTRAINT FK_ATENCION_PROFESIONAL FOREIGN KEY (PROFESIONAL_ID) REFERENCES PROFESIONAL(ID),
    CONSTRAINT FK_ATENCION_CIE10 FOREIGN KEY (DIAGNOSTICO_PRINCIPAL_ID) REFERENCES DIAGNOSTICO_CIE10(ID),
    CONSTRAINT CK_ATENCION_ESTADO CHECK (ESTADO IN ('ABIERTA', 'CERRADA')),
    CONSTRAINT CK_ATENCION_CAMPOS_CIERRE CHECK (
        ESTADO = 'ABIERTA' OR (
            FECHA_CIERRE IS NOT NULL AND
            MOTIVO_CONSULTA IS NOT NULL AND
            EVOLUCION IS NOT NULL AND
            DIAGNOSTICO_PRINCIPAL_ID IS NOT NULL AND
            INDICACIONES IS NOT NULL
        )
    )
);

CREATE INDEX IX_ATENCION_PACIENTE ON ATENCION (PACIENTE_ID, FECHA_CIERRE DESC);
CREATE INDEX IX_ATENCION_PROFESIONAL ON ATENCION (PROFESIONAL_ID, FECHA_CIERRE DESC);

-- Trigger de inmutabilidad para ATENCION (ADR-008)
CREATE OR REPLACE TRIGGER TR_ATENCION_INMUTABILIDAD
BEFORE UPDATE OR DELETE ON ATENCION
FOR EACH ROW
BEGIN
    IF DELETING THEN
        RAISE_APPLICATION_ERROR(-20001, 'Prohibido eliminar registros de atenciones clinicas.');
    END IF;
    IF UPDATING THEN
        IF :OLD.ESTADO = 'CERRADA' THEN
            RAISE_APPLICATION_ERROR(-20002, 'La atencion se encuentra CERRADA y es inmutable.');
        END IF;
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 3. SIGNO_VITAL
-- -----------------------------------------------------------------------------
CREATE TABLE SIGNO_VITAL (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ATENCION_ID NUMBER NOT NULL,
    PRESION_SISTOLICA NUMBER(3),
    PRESION_DIASTOLICA NUMBER(3),
    FRECUENCIA_CARDIACA NUMBER(3),
    FRECUENCIA_RESPIRATORIA NUMBER(2),
    TEMPERATURA NUMBER(4,1),
    SATURACION_OXIGENO NUMBER(3),
    PESO_KG NUMBER(5,2),
    TALLA_CM NUMBER(4,1),
    CONSTRAINT PK_SIGNO_VITAL PRIMARY KEY (ID),
    CONSTRAINT FK_SIGNO_VITAL_ATENCION FOREIGN KEY (ATENCION_ID) REFERENCES ATENCION(ID),
    CONSTRAINT CK_SV_SISTOLICA CHECK (PRESION_SISTOLICA IS NULL OR PRESION_SISTOLICA BETWEEN 40 AND 300),
    CONSTRAINT CK_SV_DIASTOLICA CHECK (PRESION_DIASTOLICA IS NULL OR PRESION_DIASTOLICA BETWEEN 20 AND 200),
    CONSTRAINT CK_SV_PRESION_REL CHECK (PRESION_SISTOLICA IS NULL OR PRESION_DIASTOLICA IS NULL OR PRESION_SISTOLICA > PRESION_DIASTOLICA),
    CONSTRAINT CK_SV_CARDIACA CHECK (FRECUENCIA_CARDIACA IS NULL OR FRECUENCIA_CARDIACA BETWEEN 30 AND 250),
    CONSTRAINT CK_SV_RESPIRATORIA CHECK (FRECUENCIA_RESPIRATORIA IS NULL OR FRECUENCIA_RESPIRATORIA BETWEEN 5 AND 60),
    CONSTRAINT CK_SV_TEMPERATURA CHECK (TEMPERATURA IS NULL OR TEMPERATURA BETWEEN 30.0 AND 45.0),
    CONSTRAINT CK_SV_SATURACION CHECK (SATURACION_OXIGENO IS NULL OR SATURACION_OXIGENO BETWEEN 0 AND 100),
    CONSTRAINT CK_SV_PESO CHECK (PESO_KG IS NULL OR PESO_KG BETWEEN 0.5 AND 500.0),
    CONSTRAINT CK_SV_TALLA CHECK (TALLA_CM IS NULL OR TALLA_CM BETWEEN 20.0 AND 260.0)
);

CREATE INDEX IX_SIGNO_VITAL_ATENCION ON SIGNO_VITAL (ATENCION_ID);

-- Trigger de inmutabilidad para SIGNO_VITAL (ADR-008)
CREATE OR REPLACE TRIGGER TR_SIGNO_VITAL_INMUTABILIDAD
BEFORE INSERT OR UPDATE OR DELETE ON SIGNO_VITAL
FOR EACH ROW
DECLARE
    v_estado VARCHAR2(20);
    v_atencion_id NUMBER;
BEGIN
    IF DELETING THEN
        v_atencion_id := :OLD.ATENCION_ID;
    ELSE
        v_atencion_id := :NEW.ATENCION_ID;
    END IF;

    SELECT ESTADO INTO v_estado FROM ATENCION WHERE ID = v_atencion_id;

    IF v_estado = 'CERRADA' THEN
        RAISE_APPLICATION_ERROR(-20003, 'No se pueden modificar ni registrar signos vitales en una atencion CERRADA.');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
END;
/

-- -----------------------------------------------------------------------------
-- 4. ATENCION_ENMIENDA
-- -----------------------------------------------------------------------------
CREATE TABLE ATENCION_ENMIENDA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ATENCION_ID NUMBER NOT NULL,
    PROFESIONAL_ID NUMBER NOT NULL,
    MOTIVO VARCHAR2(255 CHAR) NOT NULL,
    CONTENIDO VARCHAR2(2000 CHAR) NOT NULL,
    FECHA_ENMIENDA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_ATENCION_ENMIENDA PRIMARY KEY (ID),
    CONSTRAINT FK_ENMIENDA_ATENCION FOREIGN KEY (ATENCION_ID) REFERENCES ATENCION(ID),
    CONSTRAINT FK_ENMIENDA_PROFESIONAL FOREIGN KEY (PROFESIONAL_ID) REFERENCES PROFESIONAL(ID)
);

CREATE INDEX IX_ENMIENDA_ATENCION ON ATENCION_ENMIENDA (ATENCION_ID, FECHA_ENMIENDA ASC);

-- Trigger de inmutabilidad para ATENCION_ENMIENDA (ADR-008)
CREATE OR REPLACE TRIGGER TR_ENMIENDA_INMUTABILIDAD
BEFORE INSERT OR UPDATE OR DELETE ON ATENCION_ENMIENDA
FOR EACH ROW
DECLARE
    v_estado VARCHAR2(20);
BEGIN
    IF DELETING OR UPDATING THEN
        RAISE_APPLICATION_ERROR(-20004, 'Las enmiendas clinicas son inmutables y no se pueden modificar ni eliminar.');
    END IF;
    IF INSERTING THEN
        SELECT ESTADO INTO v_estado FROM ATENCION WHERE ID = :NEW.ATENCION_ID;
        IF v_estado <> 'CERRADA' THEN
            RAISE_APPLICATION_ERROR(-20005, 'Solo se pueden registrar enmiendas sobre atenciones en estado CERRADA.');
        END IF;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
END;
/

-- -----------------------------------------------------------------------------
-- 5. ALERGIA
-- -----------------------------------------------------------------------------
CREATE TABLE ALERGIA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PACIENTE_ID NUMBER NOT NULL,
    SUSTANCIA VARCHAR2(100 CHAR) NOT NULL,
    REACCION VARCHAR2(200 CHAR),
    SEVERIDAD VARCHAR2(20 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_ALERGIA PRIMARY KEY (ID),
    CONSTRAINT FK_ALERGIA_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(ID),
    CONSTRAINT CK_ALERGIA_SEVERIDAD CHECK (SEVERIDAD IN ('LEVE', 'MODERADA', 'GRAVE'))
);

CREATE INDEX IX_ALERGIA_PACIENTE ON ALERGIA (PACIENTE_ID);

-- -----------------------------------------------------------------------------
-- Concesión de privilegios mínimos a MEDITRIAJE_APP (ADR-008, ADR-012)
-- -----------------------------------------------------------------------------
-- Catálogo CIE-10: solo lectura
GRANT SELECT ON DIAGNOSTICO_CIE10 TO MEDITRIAJE_APP;

-- Atenciones clínicas y signos vitales: SELECT, INSERT, UPDATE (sin DELETE)
GRANT SELECT, INSERT, UPDATE ON ATENCION TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON SIGNO_VITAL TO MEDITRIAJE_APP;

-- Enmiendas clínicas: solo append-only (SELECT, INSERT, sin UPDATE ni DELETE)
GRANT SELECT, INSERT ON ATENCION_ENMIENDA TO MEDITRIAJE_APP;

-- Alergias: SELECT, INSERT, UPDATE (sin DELETE)
GRANT SELECT, INSERT, UPDATE ON ALERGIA TO MEDITRIAJE_APP;

-- -----------------------------------------------------------------------------
-- SEMILLAS: Catálogo reducido de diagnósticos CIE-10 (ficticio-seguro para MVP)
-- -----------------------------------------------------------------------------
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('J00', 'Rinofaringitis aguda (resfriado comun)');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('J02.9', 'Faringitis aguda, no especificada');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('J03.9', 'Amigdalitis aguda, no especificada');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('J06.9', 'Infeccion aguda de las vias respiratorias superiores, no especificada');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('J20.9', 'Bronquitis aguda, no especificada');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('I10', 'Hipertension esencial (primaria)');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('E11.9', 'Diabetes mellitus tipo 2 sin complicaciones');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('K29.7', 'Gastritis, no especificada');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('K21.9', 'Enfermedad por reflujo gastroesofagico sin esofagitis');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('K59.0', 'Constipacion');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('A09', 'Gastroenteritis y colitis de origen no especificado');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('M54.5', 'Lumbago no especificado');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('M25.5', 'Dolor articular');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('R10.4', 'Otros dolores abdominales y los no especificados');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('R51', 'Cefalea');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('R50.9', 'Fiebre, no especificada');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('N39.0', 'Infeccion de vias urinarias, sitio no especificado');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('B34.9', 'Infeccion viral, no especificada');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('L20.9', 'Dermatitis atopica, no especificada');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('L30.9', 'Dermatitis, no especificada');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION) VALUES ('Z00.0', 'Examen medico general');
