-- =============================================================================
-- MediTriaje 2.0 — Migración V009: Módulo de Recetas y Medicamentos (M7.1, HU-08)
-- =============================================================================
-- Tablas: MEDICAMENTO, RECETA, RECETA_DETALLE
-- Características críticas:
--   1. MEDICAMENTO: Catálogo maestro de fármacos. Solo SELECT para MEDITRIAJE_APP.
--   2. RECETA: Cabecera de prescripción médica vinculada a ATENCION, PACIENTE y PROFESIONAL.
--      Inmutable desde su creación: Trigger TR_RECETA_INMUTABILIDAD bloquea UPDATE y DELETE.
--   3. RECETA_DETALLE: Ítem prescrito con snapshot inmutable (HU-08, ADR-008).
--      Copia snapshot de nombre, principio activo, presentación y concentración.
--      Inmutable desde su creación: Trigger TR_RECETA_DETALLE_INMUTABILIDAD bloquea UPDATE y DELETE.
--   4. Privilegios mínimos (ADR-012): MEDITRIAJE_APP tiene solo SELECT en MEDICAMENTO,
--      y SELECT, INSERT en RECETA y RECETA_DETALLE (sin UPDATE ni DELETE).
--   5. Semillas de medicamentos: 16 medicamentos genéricos comunes sin dosis preestablecidas.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. MEDICAMENTO
-- -----------------------------------------------------------------------------
CREATE TABLE MEDICAMENTO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    CODIGO VARCHAR2(30 CHAR) NOT NULL,
    NOMBRE_COMERCIAL VARCHAR2(100 CHAR) NOT NULL,
    PRINCIPIO_ACTIVO VARCHAR2(100 CHAR) NOT NULL,
    PRESENTACION VARCHAR2(100 CHAR) NOT NULL,
    CONCENTRACION VARCHAR2(50 CHAR) NOT NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_MEDICAMENTO PRIMARY KEY (ID),
    CONSTRAINT UQ_MEDICAMENTO_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_MEDICAMENTO_CODIGO UNIQUE (CODIGO),
    CONSTRAINT CK_MEDICAMENTO_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
);

CREATE INDEX IX_MEDICAMENTO_BUSQUEDA ON MEDICAMENTO (PRINCIPIO_ACTIVO, NOMBRE_COMERCIAL);

-- -----------------------------------------------------------------------------
-- 2. RECETA
-- -----------------------------------------------------------------------------
CREATE TABLE RECETA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    ATENCION_ID NUMBER NOT NULL,
    PACIENTE_ID NUMBER NOT NULL,
    PROFESIONAL_ID NUMBER NOT NULL,
    VIGENCIA_DIAS NUMBER DEFAULT 30 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_RECETA PRIMARY KEY (ID),
    CONSTRAINT UQ_RECETA_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_RECETA_ATENCION FOREIGN KEY (ATENCION_ID) REFERENCES ATENCION(ID),
    CONSTRAINT FK_RECETA_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(ID),
    CONSTRAINT FK_RECETA_PROFESIONAL FOREIGN KEY (PROFESIONAL_ID) REFERENCES PROFESIONAL(ID),
    CONSTRAINT CK_RECETA_VIGENCIA CHECK (VIGENCIA_DIAS > 0)
);

CREATE INDEX IX_RECETA_PACIENTE ON RECETA (PACIENTE_ID, CREATED_AT DESC);
CREATE INDEX IX_RECETA_ATENCION ON RECETA (ATENCION_ID);

-- Trigger de inmutabilidad para RECETA (ADR-008)
CREATE OR REPLACE TRIGGER TR_RECETA_INMUTABILIDAD
BEFORE UPDATE OR DELETE ON RECETA
FOR EACH ROW
BEGIN
    IF DELETING THEN
        RAISE_APPLICATION_ERROR(-20006, 'Prohibido eliminar registros de recetas medicas.');
    END IF;
    IF UPDATING THEN
        RAISE_APPLICATION_ERROR(-20007, 'Las recetas medicas son inmutables tras su emision.');
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 3. RECETA_DETALLE
-- -----------------------------------------------------------------------------
CREATE TABLE RECETA_DETALLE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    RECETA_ID NUMBER NOT NULL,
    MEDICAMENTO_ID NUMBER NOT NULL,
    SNAPSHOT_NOMBRE VARCHAR2(100 CHAR) NOT NULL,
    SNAPSHOT_PRINCIPIO_ACTIVO VARCHAR2(100 CHAR) NOT NULL,
    SNAPSHOT_PRESENTACION VARCHAR2(100 CHAR) NOT NULL,
    SNAPSHOT_CONCENTRACION VARCHAR2(50 CHAR) NOT NULL,
    DOSIS VARCHAR2(100 CHAR) NOT NULL,
    FRECUENCIA VARCHAR2(100 CHAR) NOT NULL,
    DURACION_DIAS NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    INDICACIONES VARCHAR2(300 CHAR),
    CONSTRAINT PK_RECETA_DETALLE PRIMARY KEY (ID),
    CONSTRAINT FK_RD_RECETA FOREIGN KEY (RECETA_ID) REFERENCES RECETA(ID),
    CONSTRAINT FK_RD_MEDICAMENTO FOREIGN KEY (MEDICAMENTO_ID) REFERENCES MEDICAMENTO(ID),
    CONSTRAINT CK_RD_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CK_RD_DURACION CHECK (DURACION_DIAS > 0)
);

CREATE INDEX IX_RECETA_DETALLE_RECETA ON RECETA_DETALLE (RECETA_ID);

-- Trigger de inmutabilidad para RECETA_DETALLE (ADR-008)
CREATE OR REPLACE TRIGGER TR_RECETA_DETALLE_INMUTABILIDAD
BEFORE UPDATE OR DELETE ON RECETA_DETALLE
FOR EACH ROW
BEGIN
    IF DELETING THEN
        RAISE_APPLICATION_ERROR(-20008, 'Prohibido eliminar detalles de recetas medicas emitidas.');
    END IF;
    IF UPDATING THEN
        RAISE_APPLICATION_ERROR(-20009, 'Los detalles de recetas medicas son inmutables tras su emision.');
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 4. Concesión de privilegios mínimos a MEDITRIAJE_APP (ADR-008, ADR-012)
-- -----------------------------------------------------------------------------
-- Catálogo de medicamentos: solo lectura para la app en MVP
GRANT SELECT ON MEDICAMENTO TO MEDITRIAJE_APP;

-- Recetas y sus detalles: solo append-only (SELECT, INSERT, sin UPDATE ni DELETE)
GRANT SELECT, INSERT ON RECETA TO MEDITRIAJE_APP;
GRANT SELECT, INSERT ON RECETA_DETALLE TO MEDITRIAJE_APP;

-- -----------------------------------------------------------------------------
-- 5. SEMILLAS: Catálogo de medicamentos genéricos comunes (16 medicamentos)
-- Sin dosis recomendadas por el sistema (la dosificación es decisión profesional)
-- -----------------------------------------------------------------------------
INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000001', 'MED-ACE-500', 'Acetaminofen', 'Acetaminofen', 'Tableta', '500 mg');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000002', 'MED-IBU-400', 'Ibuprofeno', 'Ibuprofeno', 'Tableta', '400 mg');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000003', 'MED-AMX-500', 'Amoxicilina', 'Amoxicilina', 'Capsula', '500 mg');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000004', 'MED-LOR-010', 'Loratadina', 'Loratadina', 'Tableta', '10 mg');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000005', 'MED-SAL-100', 'Salbutamol Inhalador', 'Salbutamol', 'Aerosol para inhalacion', '100 mcg/dosis');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000006', 'MED-OME-020', 'Omeprazol', 'Omeprazol', 'Capsula con granulos con recubrimiento enterico', '20 mg');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000007', 'MED-LOS-050', 'Losartan Potasico', 'Losartan', 'Tableta recubierta', '50 mg');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000008', 'MED-ENA-020', 'Enalapril Maleato', 'Enalapril', 'Tableta', '20 mg');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000009', 'MED-MET-850', 'Metformina Clorhidrato', 'Metformina', 'Tableta', '850 mg');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000010', 'MED-ATV-020', 'Atorvastatina Calcica', 'Atorvastatina', 'Tableta recubierta', '20 mg');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000011', 'MED-CET-010', 'Cetirizina Diclorhidrato', 'Cetirizina', 'Tableta recubierta', '10 mg');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000012', 'MED-DIP-500', 'Dipirona Sodica', 'Metamizol Sodico', 'Tableta', '500 mg');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000013', 'MED-DXM-015', 'Dextrometorfano', 'Dextrometorfano Bromhidrato', 'Jarabe', '15 mg/5 ml');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000014', 'MED-SRO-001', 'Sales de Rehidratacion Oral', 'Electrolitos con Glucosa', 'Polvo para solucion oral', 'Sobre para 1 L');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000015', 'MED-CIP-500', 'Ciprofloxacino Clorhidrato', 'Ciprofloxacino', 'Tableta recubierta', '500 mg');

INSERT INTO MEDICAMENTO (PUBLIC_ID, CODIGO, NOMBRE_COMERCIAL, PRINCIPIO_ACTIVO, PRESENTACION, CONCENTRACION)
VALUES ('00000000-0000-7000-a000-000000000016', 'MED-NAP-250', 'Naproxeno Sodico', 'Naproxeno', 'Tableta', '250 mg');
