-- =============================================================================
-- MediTriaje 2.0 — Migración V011: Seguimiento Post-Atención y Recordatorios (F2.2, ADR-015)
-- =============================================================================
-- Cambios:
--   1. SEGUIMIENTO_POST_ATENCION: Tareas de control, evolución de síntomas, exámenes
--      y adherencia a tratamiento prescritas por el profesional tras la atención.
--      Permite registrar el reporte de evolución del paciente sin diagnósticos automáticos (§5.16).
--   2. RECORDATORIO_CITA: Trazabilidad y auditoría de notificaciones y recordatorios
--      despachados por correo (confirmación de reserva, recordatorio previo, cancelación).
--   3. Concesión de privilegios mínimos a MEDITRIAJE_APP (ADR-012).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Tabla SEGUIMIENTO_POST_ATENCION
-- -----------------------------------------------------------------------------
CREATE TABLE SEGUIMIENTO_POST_ATENCION (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    ATENCION_ID NUMBER NOT NULL,
    PACIENTE_ID NUMBER NOT NULL,
    PROFESIONAL_ID NUMBER NOT NULL,
    TIPO VARCHAR2(30 CHAR) NOT NULL,
    INDICACIONES VARCHAR2(1000 CHAR) NOT NULL,
    FECHA_SUGERIDA_CONTROL DATE NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'PENDIENTE' NOT NULL,
    FECHA_RESPUESTA_PACIENTE TIMESTAMP WITH TIME ZONE NULL,
    REPORTE_PACIENTE VARCHAR2(2000 CHAR) NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_SEGUIMIENTO PRIMARY KEY (ID),
    CONSTRAINT UQ_SEGUIMIENTO_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_SEGUIMIENTO_ATENCION FOREIGN KEY (ATENCION_ID) REFERENCES ATENCION(ID),
    CONSTRAINT FK_SEGUIMIENTO_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(ID),
    CONSTRAINT FK_SEGUIMIENTO_PROFESIONAL FOREIGN KEY (PROFESIONAL_ID) REFERENCES PROFESIONAL(ID),
    CONSTRAINT CK_SEGUIMIENTO_TIPO CHECK (TIPO IN ('CONTROL_MEDICO', 'EVOLUCION_SINTOMAS', 'EXAMEN_PENDIENTE', 'ADHERENCIA_TRATAMIENTO')),
    CONSTRAINT CK_SEGUIMIENTO_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'COMPLETADO', 'CANCELADO'))
);

CREATE INDEX IX_SEGUIMIENTO_PACIENTE ON SEGUIMIENTO_POST_ATENCION (PACIENTE_ID, ESTADO);
CREATE INDEX IX_SEGUIMIENTO_ATENCION ON SEGUIMIENTO_POST_ATENCION (ATENCION_ID);
CREATE INDEX IX_SEGUIMIENTO_PROF ON SEGUIMIENTO_POST_ATENCION (PROFESIONAL_ID);

-- -----------------------------------------------------------------------------
-- 2. Tabla RECORDATORIO_CITA
-- -----------------------------------------------------------------------------
CREATE TABLE RECORDATORIO_CITA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    CITA_ID NUMBER NOT NULL,
    PACIENTE_ID NUMBER NOT NULL,
    TIPO VARCHAR2(30 CHAR) NOT NULL,
    CANAL VARCHAR2(20 CHAR) DEFAULT 'EMAIL' NOT NULL,
    DESTINATARIO VARCHAR2(100 CHAR) NOT NULL,
    ESTADO_ENVIO VARCHAR2(20 CHAR) DEFAULT 'ENVIADO' NOT NULL,
    ERROR_MENSAJE VARCHAR2(500 CHAR) NULL,
    ENVIADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_RECORDATORIO_CITA PRIMARY KEY (ID),
    CONSTRAINT UQ_RECORDATORIO_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_RECORDATORIO_CITA FOREIGN KEY (CITA_ID) REFERENCES CITA(ID),
    CONSTRAINT FK_RECORDATORIO_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(ID),
    CONSTRAINT CK_RECORDATORIO_TIPO CHECK (TIPO IN ('CONFIRMACION_RESERVA', 'RECORDATORIO_PREVIO', 'CANCELACION')),
    CONSTRAINT CK_RECORDATORIO_CANAL CHECK (CANAL IN ('EMAIL')),
    CONSTRAINT CK_RECORDATORIO_ESTADO CHECK (ESTADO_ENVIO IN ('ENVIADO', 'FALLIDO', 'PENDIENTE'))
);

CREATE INDEX IX_RECORDATORIO_CITA ON RECORDATORIO_CITA (CITA_ID, TIPO);
CREATE INDEX IX_RECORDATORIO_PACIENTE ON RECORDATORIO_CITA (PACIENTE_ID);

-- -----------------------------------------------------------------------------
-- 3. Concesión de privilegios a MEDITRIAJE_APP (ADR-012)
-- -----------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON SEGUIMIENTO_POST_ATENCION TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON RECORDATORIO_CITA TO MEDITRIAJE_APP;
