-- =============================================================================
-- MediTriaje 2.0 — Migración V018: Enfermería, Urgencias, Episodios e Identidad Provisional (Fase U, ADR-022, ADR-023, ADR-026, ADR-027)
-- =============================================================================
-- Cambios:
--   1. Semilla del rol ROLE_ENFERMERIA en la tabla ROL (actualizando check constraint).
--   2. Tabla EPISODIO_ATENCION: Ciclo de vida asistencial hospitalario desacoplado de cita.
--   3. Tabla INGRESO_URGENCIA: Registro presencial de llegada a urgencias (idempotente, acepta NN y sin EPS).
--   4. Tabla IDENTIDAD_PROVISIONAL: Identificación temporal y reconciliación de pacientes NN indocumentados.
--   5. Tabla VALORACION_TRIAJE: Valoración clínica humana presencial I–V y PENDIENTE_VALORACION (inmutable, append-only).
--   6. Tabla ASIGNACION_ASISTENCIAL: Vínculo explícito de equipo asistencial (médico/enfermero) a episodio de urgencias.
--   7. Índices relacionales y privilegios mínimos para MEDITRIAJE_APP.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. ROL: Habilitar ROLE_ENFERMERIA
-- -----------------------------------------------------------------------------
ALTER TABLE ROL DROP CONSTRAINT CK_ROL_NOMBRE;
ALTER TABLE ROL ADD CONSTRAINT CK_ROL_NOMBRE CHECK (NOMBRE IN (
    'ROLE_PACIENTE', 'ROLE_PROFESIONAL', 'ROLE_ADMINISTRADOR', 'ROLE_FARMACEUTICO', 'ROLE_ENFERMERIA'
));

INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES (
    'ROLE_ENFERMERIA', 'Personal de enfermería y triaje presencial hospitalario'
);

-- -----------------------------------------------------------------------------
-- 2. TABLA: EPISODIO_ATENCION
-- -----------------------------------------------------------------------------
CREATE TABLE EPISODIO_ATENCION (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    PACIENTE_ID NUMBER,
    TIPO VARCHAR2(30 CHAR) NOT NULL,
    SEDE_ID NUMBER NOT NULL,
    ESTADO VARCHAR2(30 CHAR) DEFAULT 'REGISTRADO' NOT NULL,
    INGRESO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EGRESO_AT TIMESTAMP WITH TIME ZONE,
    MOTIVO_INGRESO VARCHAR2(500 CHAR),
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_EPISODIO_ATENCION PRIMARY KEY (ID),
    CONSTRAINT UQ_EPISODIO_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_EPISODIO_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(ID),
    CONSTRAINT FK_EPISODIO_SEDE FOREIGN KEY (SEDE_ID) REFERENCES SEDE(ID),
    CONSTRAINT CK_EPISODIO_TIPO CHECK (TIPO IN ('URGENCIA', 'CONSULTA', 'HOSPITALIZACION')),
    CONSTRAINT CK_EPISODIO_ESTADO CHECK (ESTADO IN (
        'REGISTRADO', 'EN_TRIAJE', 'EN_ATENCION', 'OBSERVACION', 'HOSPITALIZADO',
        'QUIROFANO', 'RECUPERACION', 'EGRESADO', 'CANCELADO'
    ))
);

CREATE INDEX IX_EPISODIO_PACIENTE ON EPISODIO_ATENCION (PACIENTE_ID);
CREATE INDEX IX_EPISODIO_SEDE_ESTADO ON EPISODIO_ATENCION (SEDE_ID, ESTADO);

-- -----------------------------------------------------------------------------
-- 3. TABLA: INGRESO_URGENCIA
-- -----------------------------------------------------------------------------
CREATE TABLE INGRESO_URGENCIA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    EPISODIO_ID NUMBER NOT NULL,
    MEDIO_LLEGADA VARCHAR2(50 CHAR) NOT NULL,
    ACOMPANANTE_NOMBRE VARCHAR2(150 CHAR),
    ACOMPANANTE_CONTACTO VARCHAR2(100 CHAR),
    MOTIVO_RESUMIDO VARCHAR2(500 CHAR) NOT NULL,
    OBSERVACIONES VARCHAR2(1000 CHAR),
    REGISTRADO_POR_USUARIO_ID NUMBER NOT NULL,
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_INGRESO_URGENCIA PRIMARY KEY (ID),
    CONSTRAINT UQ_INGRESO_URGENCIA_PUB UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_INGRESO_EPISODIO UNIQUE (EPISODIO_ID),
    CONSTRAINT FK_INGRESO_EPISODIO FOREIGN KEY (EPISODIO_ID) REFERENCES EPISODIO_ATENCION(ID),
    CONSTRAINT FK_INGRESO_USUARIO FOREIGN KEY (REGISTRADO_POR_USUARIO_ID) REFERENCES USUARIO(ID),
    CONSTRAINT CK_INGRESO_MEDIO CHECK (MEDIO_LLEGADA IN ('ESPONTANEO', 'AMBULANCIA', 'REMITIDO', 'POLICIA', 'OTRO'))
);

-- -----------------------------------------------------------------------------
-- 4. TABLA: IDENTIDAD_PROVISIONAL
-- -----------------------------------------------------------------------------
CREATE TABLE IDENTIDAD_PROVISIONAL (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    EPISODIO_ID NUMBER NOT NULL,
    CODIGO_PROVISIONAL VARCHAR2(30 CHAR) NOT NULL,
    DESCRIPCION_FISICA VARCHAR2(500 CHAR),
    EDAD_APARENTE NUMBER,
    GENERO_APARENTE VARCHAR2(20 CHAR),
    CONDICION_LLEGADA VARCHAR2(100 CHAR),
    ESTADO VARCHAR2(30 CHAR) DEFAULT 'PROVISIONAL' NOT NULL,
    VINCULADO_PACIENTE_ID NUMBER,
    CONFIRMADO_POR_USUARIO_ID NUMBER,
    FECHA_CONFIRMACION TIMESTAMP WITH TIME ZONE,
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_IDENTIDAD_PROVISIONAL PRIMARY KEY (ID),
    CONSTRAINT UQ_IDENTIDAD_PROV_PUB UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_IDENTIDAD_PROV_EPISODIO UNIQUE (EPISODIO_ID),
    CONSTRAINT UQ_IDENTIDAD_PROV_CODIGO UNIQUE (CODIGO_PROVISIONAL),
    CONSTRAINT FK_IDPROV_EPISODIO FOREIGN KEY (EPISODIO_ID) REFERENCES EPISODIO_ATENCION(ID),
    CONSTRAINT FK_IDPROV_PACIENTE FOREIGN KEY (VINCULADO_PACIENTE_ID) REFERENCES PACIENTE(ID),
    CONSTRAINT FK_IDPROV_CONFIRMADO FOREIGN KEY (CONFIRMADO_POR_USUARIO_ID) REFERENCES USUARIO(ID),
    CONSTRAINT CK_IDPROV_ESTADO CHECK (ESTADO IN ('PROVISIONAL', 'VINCULADA', 'CANCELADA')),
    CONSTRAINT CK_IDPROV_GENERO CHECK (GENERO_APARENTE IS NULL OR GENERO_APARENTE IN ('MASCULINO', 'FEMENINO', 'INDETERMINADO'))
);

CREATE INDEX IX_IDPROV_CODIGO ON IDENTIDAD_PROVISIONAL (CODIGO_PROVISIONAL);
CREATE INDEX IX_IDPROV_PACIENTE ON IDENTIDAD_PROVISIONAL (VINCULADO_PACIENTE_ID);

-- -----------------------------------------------------------------------------
-- 5. TABLA: VALORACION_TRIAJE (Inmutable, Append-Only)
-- -----------------------------------------------------------------------------
CREATE TABLE VALORACION_TRIAJE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    EPISODIO_ID NUMBER NOT NULL,
    VERSION NUMBER NOT NULL,
    NIVEL VARCHAR2(25 CHAR) NOT NULL,
    MOTIVO_CONSULTA VARCHAR2(500 CHAR) NOT NULL,
    HALLAZGOS_CLINICOS VARCHAR2(1000 CHAR),
    PRESION_ARTERIAL VARCHAR2(20 CHAR),
    FRECUENCIA_CARDIACA NUMBER,
    FRECUENCIA_RESPIRATORIA NUMBER,
    SATURACION_OXIGENO NUMBER,
    TEMPERATURA NUMBER(4,1),
    ESCALA_GLASGOW NUMBER,
    EVALUADOR_USUARIO_ID NUMBER NOT NULL,
    ES_REEVALUACION NUMBER(1) DEFAULT 0 NOT NULL,
    MOTIVO_REEVALUACION VARCHAR2(500 CHAR),
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_VALORACION_TRIAJE PRIMARY KEY (ID),
    CONSTRAINT UQ_VAL_TRIAJE_PUB UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_VAL_TRIAJE_EP_VER UNIQUE (EPISODIO_ID, VERSION),
    CONSTRAINT FK_VAL_TRIAJE_EPISODIO FOREIGN KEY (EPISODIO_ID) REFERENCES EPISODIO_ATENCION(ID),
    CONSTRAINT FK_VAL_TRIAJE_USUARIO FOREIGN KEY (EVALUADOR_USUARIO_ID) REFERENCES USUARIO(ID),
    CONSTRAINT CK_VAL_TRIAJE_NIVEL CHECK (NIVEL IN ('I', 'II', 'III', 'IV', 'V', 'PENDIENTE_VALORACION'))
);

CREATE INDEX IX_VAL_TRIAJE_EPISODIO ON VALORACION_TRIAJE (EPISODIO_ID);

-- Trigger de inmutabilidad estricta: bloquea UPDATE y DELETE
CREATE OR REPLACE TRIGGER TR_VAL_TRIAJE_INMUTABLE
BEFORE UPDATE OR DELETE ON VALORACION_TRIAJE
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20030, 'Las valoraciones clinicas de triaje son inmutables: las reevaluaciones deben registrarse como un nuevo evento append-only.');
END;
/

-- -----------------------------------------------------------------------------
-- 6. TABLA: ASIGNACION_ASISTENCIAL
-- -----------------------------------------------------------------------------
CREATE TABLE ASIGNACION_ASISTENCIAL (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    EPISODIO_ID NUMBER NOT NULL,
    PROFESIONAL_ID NUMBER NOT NULL,
    FUNCION VARCHAR2(50 CHAR) NOT NULL,
    ASIGNADO_POR_USUARIO_ID NUMBER NOT NULL,
    FECHA_INICIO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP WITH TIME ZONE,
    ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_ASIGNACION_ASISTENCIAL PRIMARY KEY (ID),
    CONSTRAINT UQ_ASIG_ASIST_PUB UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_ASIG_EPISODIO FOREIGN KEY (EPISODIO_ID) REFERENCES EPISODIO_ATENCION(ID),
    CONSTRAINT FK_ASIG_PROFESIONAL FOREIGN KEY (PROFESIONAL_ID) REFERENCES PROFESIONAL(ID),
    CONSTRAINT FK_ASIG_USUARIO FOREIGN KEY (ASIGNADO_POR_USUARIO_ID) REFERENCES USUARIO(ID),
    CONSTRAINT CK_ASIG_FUNCION CHECK (FUNCION IN ('MEDICO_TRATANTE', 'ENFERMERO_CARGO', 'INTERCONSULTOR'))
);

CREATE INDEX IX_ASIG_EPISODIO_ACTIVO ON ASIGNACION_ASISTENCIAL (EPISODIO_ID, ACTIVO);
CREATE INDEX IX_ASIG_PROF_ACTIVO ON ASIGNACION_ASISTENCIAL (PROFESIONAL_ID, ACTIVO);

-- -----------------------------------------------------------------------------
-- 7. PRIVILEGIOS MÍNIMOS A MEDITRIAJE_APP (ADR-012)
-- -----------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON EPISODIO_ATENCION TO MEDITRIAJE_APP;
GRANT SELECT, INSERT ON INGRESO_URGENCIA TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON IDENTIDAD_PROVISIONAL TO MEDITRIAJE_APP;
GRANT SELECT, INSERT ON VALORACION_TRIAJE TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON ASIGNACION_ASISTENCIAL TO MEDITRIAJE_APP;
