-- =============================================================================
-- MediTriaje 2.0 — Migración V019: Gestión Hospitalaria, Camas, Movimientos y Egresos (Fase H, ADR-024, ADR-027)
-- =============================================================================
-- Tablas creadas:
--   1. AREA_HOSPITALARIA: Pabellones, salas de urgencias, UCI, quirófanos y hospitalización general por sede.
--   2. HABITACION_SALA: Salas y habitaciones individuales o compartidas por área.
--   3. CAMA_HOSPITALARIA: Recursos de camas con control de estado (DISPONIBLE, OCUPADA, LIMPIEZA, MANTENIMIENTO, INACTIVA).
--   4. OCUPACION_CAMA: Asignación longitudinal de camas a episodios de atención.
--   5. MOVIMIENTO_PACIENTE: Historial longitudinal e inmutable de traslados intrahospitalarios.
--   6. PROCEDIMIENTO_HOSPITALARIO: Cirugías, procedimientos invasivos y tiempos de recuperación.
--   7. EGRESO_HOSPITALARIO: Cierre asistencial, destino del egreso (alta, remisión, etc.) y liberación de cama.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. TABLA: AREA_HOSPITALARIA
-- -----------------------------------------------------------------------------
CREATE TABLE AREA_HOSPITALARIA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    SEDE_ID NUMBER NOT NULL,
    CODIGO VARCHAR2(30 CHAR) NOT NULL,
    NOMBRE VARCHAR2(100 CHAR) NOT NULL,
    TIPO VARCHAR2(30 CHAR) NOT NULL,
    PISO VARCHAR2(20 CHAR),
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVA' NOT NULL,
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_AREA_HOSPITALARIA PRIMARY KEY (ID),
    CONSTRAINT UQ_AREA_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_AREA_SEDE_CODIGO UNIQUE (SEDE_ID, CODIGO),
    CONSTRAINT FK_AREA_SEDE FOREIGN KEY (SEDE_ID) REFERENCES SEDE(ID),
    CONSTRAINT CK_AREA_TIPO CHECK (TIPO IN (
        'URGENCIAS', 'OBSERVACION', 'HOSPITALIZACION_GENERAL', 'UCI_ADULTOS',
        'UCI_PEDIATRICA', 'QUIROFANO', 'RECUPERACION', 'SALA_PARTOS'
    )),
    CONSTRAINT CK_AREA_ESTADO CHECK (ESTADO IN ('ACTIVA', 'INACTIVA', 'MANTENIMIENTO'))
);

CREATE INDEX IX_AREA_SEDE ON AREA_HOSPITALARIA (SEDE_ID);

-- -----------------------------------------------------------------------------
-- 2. TABLA: HABITACION_SALA
-- -----------------------------------------------------------------------------
CREATE TABLE HABITACION_SALA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    AREA_ID NUMBER NOT NULL,
    CODIGO VARCHAR2(30 CHAR) NOT NULL,
    TIPO VARCHAR2(30 CHAR) DEFAULT 'COMPARTIDA' NOT NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVA' NOT NULL,
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_HABITACION_SALA PRIMARY KEY (ID),
    CONSTRAINT UQ_HABITACION_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_HABITACION_AREA_CODIGO UNIQUE (AREA_ID, CODIGO),
    CONSTRAINT FK_HABITACION_AREA FOREIGN KEY (AREA_ID) REFERENCES AREA_HOSPITALARIA(ID),
    CONSTRAINT CK_HABITACION_TIPO CHECK (TIPO IN ('INDIVIDUAL', 'COMPARTIDA', 'AISLAMIENTO', 'QUIROFANO', 'SALA_COMUN')),
    CONSTRAINT CK_HABITACION_ESTADO CHECK (ESTADO IN ('ACTIVA', 'INACTIVA', 'DESINFECCION'))
);

CREATE INDEX IX_HABITACION_AREA ON HABITACION_SALA (AREA_ID);

-- -----------------------------------------------------------------------------
-- 3. TABLA: CAMA_HOSPITALARIA
-- -----------------------------------------------------------------------------
CREATE TABLE CAMA_HOSPITALARIA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    HABITACION_ID NUMBER NOT NULL,
    CODIGO VARCHAR2(30 CHAR) NOT NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'DISPONIBLE' NOT NULL,
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_CAMA_HOSPITALARIA PRIMARY KEY (ID),
    CONSTRAINT UQ_CAMA_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_CAMA_HABITACION_CODIGO UNIQUE (HABITACION_ID, CODIGO),
    CONSTRAINT FK_CAMA_HABITACION FOREIGN KEY (HABITACION_ID) REFERENCES HABITACION_SALA(ID),
    CONSTRAINT CK_CAMA_ESTADO CHECK (ESTADO IN (
        'DISPONIBLE', 'OCUPADA', 'LIMPIEZA', 'MANTENIMIENTO', 'INACTIVA'
    ))
);

CREATE INDEX IX_CAMA_HABITACION_ESTADO ON CAMA_HOSPITALARIA (HABITACION_ID, ESTADO);

-- -----------------------------------------------------------------------------
-- 4. TABLA: OCUPACION_CAMA
-- -----------------------------------------------------------------------------
CREATE TABLE OCUPACION_CAMA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    EPISODIO_ID NUMBER NOT NULL,
    CAMA_ID NUMBER NOT NULL,
    INICIO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIN_AT TIMESTAMP WITH TIME ZONE,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVA' NOT NULL,
    ASIGNADO_POR_USUARIO_ID NUMBER NOT NULL,
    MOTIVO_ASIGNACION VARCHAR2(500 CHAR),
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_OCUPACION_CAMA PRIMARY KEY (ID),
    CONSTRAINT UQ_OCUPACION_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_OCUPACION_EPISODIO FOREIGN KEY (EPISODIO_ID) REFERENCES EPISODIO_ATENCION(ID),
    CONSTRAINT FK_OCUPACION_CAMA FOREIGN KEY (CAMA_ID) REFERENCES CAMA_HOSPITALARIA(ID),
    CONSTRAINT FK_OCUPACION_USUARIO FOREIGN KEY (ASIGNADO_POR_USUARIO_ID) REFERENCES USUARIO(ID),
    CONSTRAINT CK_OCUPACION_ESTADO CHECK (ESTADO IN ('ACTIVA', 'FINALIZADA', 'CANCELADA'))
);

CREATE INDEX IX_OCUPACION_EPISODIO ON OCUPACION_CAMA (EPISODIO_ID);
CREATE INDEX IX_OCUPACION_CAMA_ACTIVA ON OCUPACION_CAMA (CAMA_ID, ESTADO);

-- -----------------------------------------------------------------------------
-- 5. TABLA: MOVIMIENTO_PACIENTE (Historial Longitudinal de Traslados)
-- -----------------------------------------------------------------------------
CREATE TABLE MOVIMIENTO_PACIENTE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    EPISODIO_ID NUMBER NOT NULL,
    AREA_ORIGEN_ID NUMBER,
    AREA_DESTINO_ID NUMBER NOT NULL,
    CAMA_ORIGEN_ID NUMBER,
    CAMA_DESTINO_ID NUMBER,
    FECHA_MOVIMIENTO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MOTIVO_TRASLADO VARCHAR2(500 CHAR) NOT NULL,
    REGISTRADO_POR_USUARIO_ID NUMBER NOT NULL,
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_MOVIMIENTO_PACIENTE PRIMARY KEY (ID),
    CONSTRAINT UQ_MOVIMIENTO_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_MOVIMIENTO_EPISODIO FOREIGN KEY (EPISODIO_ID) REFERENCES EPISODIO_ATENCION(ID),
    CONSTRAINT FK_MOVIMIENTO_AREA_ORIGEN FOREIGN KEY (AREA_ORIGEN_ID) REFERENCES AREA_HOSPITALARIA(ID),
    CONSTRAINT FK_MOVIMIENTO_AREA_DESTINO FOREIGN KEY (AREA_DESTINO_ID) REFERENCES AREA_HOSPITALARIA(ID),
    CONSTRAINT FK_MOVIMIENTO_CAMA_ORIGEN FOREIGN KEY (CAMA_ORIGEN_ID) REFERENCES CAMA_HOSPITALARIA(ID),
    CONSTRAINT FK_MOVIMIENTO_CAMA_DESTINO FOREIGN KEY (CAMA_DESTINO_ID) REFERENCES CAMA_HOSPITALARIA(ID),
    CONSTRAINT FK_MOVIMIENTO_USUARIO FOREIGN KEY (REGISTRADO_POR_USUARIO_ID) REFERENCES USUARIO(ID)
);

CREATE INDEX IX_MOVIMIENTO_EPISODIO ON MOVIMIENTO_PACIENTE (EPISODIO_ID, FECHA_MOVIMIENTO);

-- Trigger de inmutabilidad append-only para movimientos intrahospitalarios
CREATE OR REPLACE TRIGGER TRG_MOVIMIENTO_INMUTABLE
BEFORE UPDATE OR DELETE ON MOVIMIENTO_PACIENTE
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20011, 'Los registros de movimientos y traslados intrahospitalarios son inmutables para fines de auditoría.');
END;
/

-- -----------------------------------------------------------------------------
-- 6. TABLA: PROCEDIMIENTO_HOSPITALARIO (Quirófano, Cirugía y Recuperación)
-- -----------------------------------------------------------------------------
CREATE TABLE PROCEDIMIENTO_HOSPITALARIO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    EPISODIO_ID NUMBER NOT NULL,
    TIPO_PROCEDIMIENTO VARCHAR2(100 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(1000 CHAR) NOT NULL,
    PROFESIONAL_ID NUMBER NOT NULL,
    SALA_ID NUMBER,
    ESTADO VARCHAR2(30 CHAR) DEFAULT 'PROGRAMADO' NOT NULL,
    INICIO_AT TIMESTAMP WITH TIME ZONE,
    FIN_AT TIMESTAMP WITH TIME ZONE,
    OBSERVACIONES VARCHAR2(1000 CHAR),
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_PROCEDIMIENTO_HOSP PRIMARY KEY (ID),
    CONSTRAINT UQ_PROCEDIMIENTO_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_PROCEDIMIENTO_EPISODIO FOREIGN KEY (EPISODIO_ID) REFERENCES EPISODIO_ATENCION(ID),
    CONSTRAINT FK_PROCEDIMIENTO_PROFESIONAL FOREIGN KEY (PROFESIONAL_ID) REFERENCES PROFESIONAL_SALUD(ID),
    CONSTRAINT FK_PROCEDIMIENTO_SALA FOREIGN KEY (SALA_ID) REFERENCES HABITACION_SALA(ID),
    CONSTRAINT CK_PROCEDIMIENTO_ESTADO CHECK (ESTADO IN (
        'PROGRAMADO', 'EN_CURSO', 'RECUPERACION', 'FINALIZADO', 'CANCELADO'
    ))
);

CREATE INDEX IX_PROCEDIMIENTO_EPISODIO ON PROCEDIMIENTO_HOSPITALARIO (EPISODIO_ID);

-- -----------------------------------------------------------------------------
-- 7. TABLA: EGRESO_HOSPITALARIO
-- -----------------------------------------------------------------------------
CREATE TABLE EGRESO_HOSPITALARIO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    EPISODIO_ID NUMBER NOT NULL,
    MEDICO_EGRESO_ID NUMBER NOT NULL,
    FECHA_EGRESO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TIPO_DESTINO VARCHAR2(50 CHAR) NOT NULL,
    DIAGNOSTICO_EGRESO VARCHAR2(500 CHAR) NOT NULL,
    EPICRISIS_RESUMEN VARCHAR2(2000 CHAR),
    PLAN_MANEJO VARCHAR2(1000 CHAR),
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_EGRESO_HOSPITALARIO PRIMARY KEY (ID),
    CONSTRAINT UQ_EGRESO_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_EGRESO_EPISODIO UNIQUE (EPISODIO_ID),
    CONSTRAINT FK_EGRESO_EPISODIO FOREIGN KEY (EPISODIO_ID) REFERENCES EPISODIO_ATENCION(ID),
    CONSTRAINT FK_EGRESO_MEDICO FOREIGN KEY (MEDICO_EGRESO_ID) REFERENCES PROFESIONAL_SALUD(ID),
    CONSTRAINT CK_EGRESO_DESTINO CHECK (TIPO_DESTINO IN (
        'ALTA_DOMICILIO', 'CONTRAREFERENCIA', 'TRASLADO_OTRA_IPS', 'HOSPITALIZACION_DOMICILIARIA', 'FALLECIMIENTO'
    ))
);

CREATE INDEX IX_EGRESO_MEDICO ON EGRESO_HOSPITALARIO (MEDICO_EGRESO_ID);

-- -----------------------------------------------------------------------------
-- 8. PERMISOS PARA EL USUARIO DE APLICACIÓN
-- -----------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON AREA_HOSPITALARIA TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON HABITACION_SALA TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON CAMA_HOSPITALARIA TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON OCUPACION_CAMA TO MEDITRIAJE_APP;
GRANT SELECT, INSERT ON MOVIMIENTO_PACIENTE TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON PROCEDIMIENTO_HOSPITALARIO TO MEDITRIAJE_APP;
GRANT SELECT, INSERT ON EGRESO_HOSPITALARIO TO MEDITRIAJE_APP;
