-- =============================================================================
-- MediTriaje 2.0 — Migración V020: Afiliaciones EPS, Aseguramiento y Citas Avanzadas (Fases A y C, ADR-025, ADR-026)
-- =============================================================================
-- Tablas creadas:
--   1. ENTIDAD_EPS: Directorio institucional de EPS autorizadas por MinSalud.
--   2. AFILIACION_PACIENTE: Registro de aseguramiento, régimen y estado de afiliación.
--   3. LOTE_IMPORTACION_EPS: Encabezado de auditoría de lotes de importación Excel (A02, A03, A06).
--   4. DETALLE_IMPORTACION_EPS: Staging y preview fila a fila de importación masiva.
--   5. AUSENCIA_MEDICA: Bloqueo de agenda médica por permisos, incapacidades o feriados (C02).
--   6. REPRESENTACION_LEGAL: Registro auditado de menores de edad y tutores legales (C03).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. TABLA: ENTIDAD_EPS
-- -----------------------------------------------------------------------------
CREATE TABLE ENTIDAD_EPS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    CODIGO_MINSALUD VARCHAR2(20 CHAR) NOT NULL,
    NOMBRE VARCHAR2(150 CHAR) NOT NULL,
    NIT VARCHAR2(20 CHAR),
    REGIMEN_HABITUAL VARCHAR2(30 CHAR) DEFAULT 'CONTRIBUTIVO' NOT NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVA' NOT NULL,
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_ENTIDAD_EPS PRIMARY KEY (ID),
    CONSTRAINT UQ_EPS_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_EPS_CODIGO UNIQUE (CODIGO_MINSALUD),
    CONSTRAINT CK_EPS_REGIMEN CHECK (REGIMEN_HABITUAL IN ('CONTRIBUTIVO', 'SUBSIDIADO', 'ESPECIAL', 'MIXTO')),
    CONSTRAINT CK_EPS_ESTADO CHECK (ESTADO IN ('ACTIVA', 'INACTIVA', 'LIQUIDACION'))
);

CREATE INDEX IX_EPS_CODIGO_ESTADO ON ENTIDAD_EPS (CODIGO_MINSALUD, ESTADO);

-- Semilla de EPS colombianas comunes en Valledupar y la Costa Caribe
INSERT INTO ENTIDAD_EPS (PUBLIC_ID, CODIGO_MINSALUD, NOMBRE, NIT, REGIMEN_HABITUAL, ESTADO)
VALUES ('eps-nueva-eps-001', 'EPS037', 'NUEVA EPS S.A.', '900156264-2', 'MIXTO', 'ACTIVA');

INSERT INTO ENTIDAD_EPS (PUBLIC_ID, CODIGO_MINSALUD, NOMBRE, NIT, REGIMEN_HABITUAL, ESTADO)
VALUES ('eps-sanitas-002', 'EPS005', 'ENTIDAD PROMOTORA DE SALUD SANITAS S.A.S.', '800251440-6', 'CONTRIBUTIVO', 'ACTIVA');

INSERT INTO ENTIDAD_EPS (PUBLIC_ID, CODIGO_MINSALUD, NOMBRE, NIT, REGIMEN_HABITUAL, ESTADO)
VALUES ('eps-cajacopi-003', 'CCFC55', 'CAJACOPI EPS S.A.S.', '901543761-0', 'SUBSIDIADO', 'ACTIVA');

INSERT INTO ENTIDAD_EPS (PUBLIC_ID, CODIGO_MINSALUD, NOMBRE, NIT, REGIMEN_HABITUAL, ESTADO)
VALUES ('eps-salud-total-004', 'EPS002', 'SALUD TOTAL S.A. E.P.S.', '800130907-4', 'CONTRIBUTIVO', 'ACTIVA');

INSERT INTO ENTIDAD_EPS (PUBLIC_ID, CODIGO_MINSALUD, NOMBRE, NIT, REGIMEN_HABITUAL, ESTADO)
VALUES ('eps-mutual-ser-005', 'ESS118', 'MUTUAL SER EPS', '806008394-6', 'SUBSIDIADO', 'ACTIVA');

-- -----------------------------------------------------------------------------
-- 2. TABLA: AFILIACION_PACIENTE
-- -----------------------------------------------------------------------------
CREATE TABLE AFILIACION_PACIENTE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    PACIENTE_ID NUMBER,
    TIPO_DOCUMENTO VARCHAR2(10 CHAR) NOT NULL,
    NUMERO_DOCUMENTO VARCHAR2(30 CHAR) NOT NULL,
    EPS_ID NUMBER NOT NULL,
    REGIMEN VARCHAR2(30 CHAR) NOT NULL,
    TIPO_AFILIADO VARCHAR2(30 CHAR) DEFAULT 'COTIZANTE' NOT NULL,
    ESTADO VARCHAR2(30 CHAR) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_AFILIACION DATE,
    FUENTE_VERIFICACION VARCHAR2(50 CHAR) DEFAULT 'CARGA_MASIVA' NOT NULL,
    ULTIMA_VERIFICACION_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_AFILIACION_PACIENTE PRIMARY KEY (ID),
    CONSTRAINT UQ_AFILIACION_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT UQ_AFILIACION_DOC UNIQUE (TIPO_DOCUMENTO, NUMERO_DOCUMENTO),
    CONSTRAINT FK_AFILIACION_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(ID),
    CONSTRAINT FK_AFILIACION_EPS FOREIGN KEY (EPS_ID) REFERENCES ENTIDAD_EPS(ID),
    CONSTRAINT CK_AFILIACION_REGIMEN CHECK (REGIMEN IN ('CONTRIBUTIVO', 'SUBSIDIADO', 'ESPECIAL', 'NO_ASEGURADO')),
    CONSTRAINT CK_AFILIACION_ESTADO CHECK (ESTADO IN ('ACTIVO', 'SUSPENDIDO', 'RETIRADO', 'NO_AFILIADO')),
    CONSTRAINT CK_AFILIACION_TIPO_AFIL CHECK (TIPO_AFILIADO IN ('COTIZANTE', 'BENEFICIARIO', 'ADICIONAL', 'CABEZA_FAMILIA'))
);

CREATE INDEX IX_AFILIACION_PACIENTE_ID ON AFILIACION_PACIENTE (PACIENTE_ID);
CREATE INDEX IX_AFILIACION_EPS_ESTADO ON AFILIACION_PACIENTE (EPS_ID, ESTADO);

-- -----------------------------------------------------------------------------
-- 3. TABLA: LOTE_IMPORTACION_EPS
-- -----------------------------------------------------------------------------
CREATE TABLE LOTE_IMPORTACION_EPS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    NOMBRE_ARCHIVO VARCHAR2(255 CHAR) NOT NULL,
    HASH_SHA256 VARCHAR2(64 CHAR) NOT NULL,
    EPS_ID NUMBER NOT NULL,
    TOTAL_FILAS NUMBER DEFAULT 0 NOT NULL,
    FILAS_VALIDAS NUMBER DEFAULT 0 NOT NULL,
    FILAS_FALLIDAS NUMBER DEFAULT 0 NOT NULL,
    ESTADO VARCHAR2(30 CHAR) DEFAULT 'PREVIEW' NOT NULL,
    SUBIDO_POR_USUARIO_ID NUMBER NOT NULL,
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PROCESADO_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT PK_LOTE_IMPORTACION PRIMARY KEY (ID),
    CONSTRAINT UQ_LOTE_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_LOTE_EPS FOREIGN KEY (EPS_ID) REFERENCES ENTIDAD_EPS(ID),
    CONSTRAINT FK_LOTE_USUARIO FOREIGN KEY (SUBIDO_POR_USUARIO_ID) REFERENCES USUARIO(ID),
    CONSTRAINT CK_LOTE_ESTADO CHECK (ESTADO IN ('PREVIEW', 'PROCESADO', 'RECHAZADO', 'ERROR'))
);

CREATE INDEX IX_LOTE_EPS_CREADO ON LOTE_IMPORTACION_EPS (EPS_ID, CREADO_AT);

-- -----------------------------------------------------------------------------
-- 4. TABLA: DETALLE_IMPORTACION_EPS (Staging de Validación)
-- -----------------------------------------------------------------------------
CREATE TABLE DETALLE_IMPORTACION_EPS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LOTE_ID NUMBER NOT NULL,
    NUMERO_FILA NUMBER NOT NULL,
    TIPO_DOCUMENTO VARCHAR2(10 CHAR),
    NUMERO_DOCUMENTO VARCHAR2(30 CHAR),
    NOMBRES VARCHAR2(100 CHAR),
    APELLIDOS VARCHAR2(100 CHAR),
    REGIMEN VARCHAR2(30 CHAR),
    TIPO_AFILIADO VARCHAR2(30 CHAR),
    ESTADO_FILA VARCHAR2(20 CHAR) NOT NULL,
    ERROR_MOTIVO VARCHAR2(500 CHAR),
    CONSTRAINT PK_DETALLE_IMPORTACION PRIMARY KEY (ID),
    CONSTRAINT FK_DETALLE_LOTE FOREIGN KEY (LOTE_ID) REFERENCES LOTE_IMPORTACION_EPS(ID) ON DELETE CASCADE,
    CONSTRAINT CK_DETALLE_ESTADO CHECK (ESTADO_FILA IN ('VALIDO', 'ERROR', 'IGNORADO'))
);

CREATE INDEX IX_DETALLE_LOTE_FILA ON DETALLE_IMPORTACION_EPS (LOTE_ID, ESTADO_FILA);

-- -----------------------------------------------------------------------------
-- 5. TABLA: AUSENCIA_MEDICA (C02 - Feriados, Incapacidades y Bloqueos de Agenda)
-- -----------------------------------------------------------------------------
CREATE TABLE AUSENCIA_MEDICA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    PROFESIONAL_ID NUMBER NOT NULL,
    FECHA_INICIO TIMESTAMP WITH TIME ZONE NOT NULL,
    FECHA_FIN TIMESTAMP WITH TIME ZONE NOT NULL,
    MOTIVO VARCHAR2(500 CHAR) NOT NULL,
    ESTADO VARCHAR2(20 CHAR) DEFAULT 'ACTIVA' NOT NULL,
    REGISTRADO_POR_USUARIO_ID NUMBER NOT NULL,
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_AUSENCIA_MEDICA PRIMARY KEY (ID),
    CONSTRAINT UQ_AUSENCIA_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_AUSENCIA_PROFESIONAL FOREIGN KEY (PROFESIONAL_ID) REFERENCES PROFESIONAL_SALUD(ID),
    CONSTRAINT FK_AUSENCIA_USUARIO FOREIGN KEY (REGISTRADO_POR_USUARIO_ID) REFERENCES USUARIO(ID),
    CONSTRAINT CK_AUSENCIA_ESTADO CHECK (ESTADO IN ('ACTIVA', 'CANCELADA'))
);

CREATE INDEX IX_AUSENCIA_PROF_FECHAS ON AUSENCIA_MEDICA (PROFESIONAL_ID, FECHA_INICIO, FECHA_FIN);

-- -----------------------------------------------------------------------------
-- 6. TABLA: REPRESENTACION_LEGAL (C03 - Menores de Edad y Custodia)
-- -----------------------------------------------------------------------------
CREATE TABLE REPRESENTACION_LEGAL (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    PUBLIC_ID VARCHAR2(36 CHAR) NOT NULL,
    PACIENTE_MENOR_ID NUMBER NOT NULL,
    REPRESENTANTE_PACIENTE_ID NUMBER NOT NULL,
    PARENTESCO VARCHAR2(30 CHAR) NOT NULL,
    DOCUMENTO_SOPORTE VARCHAR2(100 CHAR),
    VERIFICADO NUMBER(1) DEFAULT 1 NOT NULL,
    CREADO_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_REPRESENTACION_LEGAL PRIMARY KEY (ID),
    CONSTRAINT UQ_REP_LEGAL_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_REP_PACIENTE_MENOR FOREIGN KEY (PACIENTE_MENOR_ID) REFERENCES PACIENTE(ID),
    CONSTRAINT FK_REP_PACIENTE_REP FOREIGN KEY (REPRESENTANTE_PACIENTE_ID) REFERENCES PACIENTE(ID),
    CONSTRAINT CK_REP_PARENTESCO CHECK (PARENTESCO IN ('PADRE', 'MADRE', 'TUTOR_LEGAL', 'CUIDADOR_AUTORIZADO')),
    CONSTRAINT CK_REP_VERIFICADO CHECK (VERIFICADO IN (0, 1))
);

CREATE INDEX IX_REP_LEGAL_MENOR ON REPRESENTACION_LEGAL (PACIENTE_MENOR_ID);

-- -----------------------------------------------------------------------------
-- 7. PERMISOS PARA EL USUARIO DE APLICACIÓN
-- -----------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON ENTIDAD_EPS TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON AFILIACION_PACIENTE TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON LOTE_IMPORTACION_EPS TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, DELETE ON DETALLE_IMPORTACION_EPS TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON AUSENCIA_MEDICA TO MEDITRIAJE_APP;
GRANT SELECT, INSERT, UPDATE ON REPRESENTACION_LEGAL TO MEDITRIAJE_APP;
