-- ============================================================================
-- V021: Analítica Hospitalaria, Alertas Operativas y QR de Seguimiento (Lote O)
-- Plataforma MediTriaje 2.0 (ADR-027, ADR-028, Res 5596/2015, Res 2275/2023)
-- ============================================================================

-- 1. Tabla de Alertas Operativas de Saturación y Demora (O02)
CREATE TABLE ALERTA_OPERATIVA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PUBLIC_ID VARCHAR2(36) NOT NULL UNIQUE,
    SEDE_ID NUMBER NOT NULL REFERENCES SEDE(ID),
    TIPO_ALERTA VARCHAR2(50) NOT NULL,
    NIVEL_SEVERIDAD VARCHAR2(20) NOT NULL,
    MENSAJE VARCHAR2(500) NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVA' NOT NULL,
    RECONOCIDO_POR_USUARIO_ID NUMBER REFERENCES USUARIO(ID),
    RECONOCIDO_AT TIMESTAMP,
    MOTIVO_RECONOCIMIENTO VARCHAR2(500),
    CREADO_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CHK_ALERTA_ESTADO CHECK (ESTADO IN ('ACTIVA', 'RECONOCIDA', 'RESUELTA')),
    CONSTRAINT CHK_ALERTA_SEVERIDAD CHECK (NIVEL_SEVERIDAD IN ('CRITICA', 'ALTA', 'MEDIA', 'INFORMATIVA'))
);

CREATE INDEX IDX_ALERTA_SEDE_ESTADO ON ALERTA_OPERATIVA(SEDE_ID, ESTADO);
CREATE INDEX IDX_ALERTA_PUBLIC_ID ON ALERTA_OPERATIVA(PUBLIC_ID);

-- 2. Tabla de Seguimiento Intrahospitalario por Código QR Operativo Seguro (O03)
-- No expone historia clínica ni diagnósticos; solo identificador opaco y localización.
CREATE TABLE SEGUIMIENTO_INTRAHOSPITALARIO_QR (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PUBLIC_ID VARCHAR2(36) NOT NULL UNIQUE,
    EPISODIO_ID NUMBER NOT NULL REFERENCES EPISODIO_ATENCION(ID),
    CODIGO_QR_TOKEN VARCHAR2(100) NOT NULL UNIQUE,
    UBICACION_ACTUAL_TEXTO VARCHAR2(200),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CREADO_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRA_AT TIMESTAMP,
    CONSTRAINT CHK_SEGUIMIENTO_QR_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO', 'REVOCADO'))
);

CREATE INDEX IDX_SEGUIMIENTO_QR_TOKEN ON SEGUIMIENTO_INTRAHOSPITALARIO_QR(CODIGO_QR_TOKEN);
CREATE INDEX IDX_SEGUIMIENTO_QR_EPISODIO ON SEGUIMIENTO_INTRAHOSPITALARIO_QR(EPISODIO_ID);

-- Comentarios explicativos de auditoría clínica
COMMENT ON TABLE ALERTA_OPERATIVA IS 'Alertas operativas de saturación hospitalaria y demoras en triage con reconocimiento auditado (O02)';
COMMENT ON TABLE SEGUIMIENTO_INTRAHOSPITALARIO_QR IS 'Tokens seguros para códigos QR en manillas de pacientes sin datos clínicos expuestos (O03)';
