spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:}
    username: ${DB_USER:MEDITRIAJE_APP}
    password: ${DB_PASSWORD:}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: MediTriajeHikariPool-Dev
      connection-test-query: SELECT 1 FROM DUAL
      connection-init-sql: "BEGIN EXECUTE IMMEDIATE 'ALTER SESSION SET TIME_ZONE = ''America/Bogota'''; EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = MEDITRIAJE_OWNER'; END;"
      maximum-pool-size: 5
      minimum-idle: 1
      initialization-fail-timeout: -1
  flyway:
    enabled: ${FLYWAY_ENABLED:false}
    user: ${FLYWAY_USER:MEDITRIAJE_OWNER}
    password: ${FLYWAY_PASSWORD:}

cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://127.0.0.1:3000,http://localhost:5500}

security:
  jwt:
    secret: ${JWT_SECRET:dev-secret-key-must-be-at-least-256-bits-long-for-hmac-sha256}
    expiration-minutes: 15
    refresh-expiration-days: 7
